version: 2

project_name: canhazgpu

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: canhazgpu

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: false
    files:
      - autocomplete_canhazgpu.sh
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew formula disabled
# brews:
#   - skip_upload: true

release:
  github:
    owner: russellb
    name: canhazgpu
  draft: false
  prerelease: auto
  mode: replace
  header: |
    # canhazgpu - GPU Reservation Tool
    
    A GPU reservation tool for single host shared development systems. Coordinates GPU access across multiple users and processes using Redis backend with comprehensive validation and automatic cleanup.
