apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodecachestatuses.canhazgpu.dev
spec:
  group: canhazgpu.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
            properties:
              nodeName:
                type: string
              images:
                type: array
                items:
                  type: object
                  properties:
                    ref:
                      type: string
                    present:
                      type: boolean
                    status:
                      type: string
                      enum: ["pulling", "ready", "failed"]
                    digest:
                      type: string
                    lastChecked:
                      type: string
                      format: date-time
                    message:
                      type: string
              gitRepos:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    ref:
                      type: string
                    path:
                      type: string
                    url:
                      type: string
                    branch:
                      type: string
                    commit:
                      type: string
                    present:
                      type: boolean
                    status:
                      type: string
                      enum: ["pulling", "ready", "failed"]
                    synced:
                      type: boolean
                    lastSync:
                      type: string
                      format: date-time
                    message:
                      type: string
              errors:
                type: array
                items:
                  type: string
              lastUpdate:
                type: string
                format: date-time
    subresources:
      status: {}
  scope: Cluster
  names:
    plural: nodecachestatuses
    singular: nodecachestatus
    kind: NodeCacheStatus