apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: canhazgpu-kubeletplugin
  namespace: canhazgpu-system
  labels:
    app: canhazgpu-kubeletplugin
spec:
  selector:
    matchLabels:
      app: canhazgpu-kubeletplugin
  template:
    metadata:
      labels:
        app: canhazgpu-kubeletplugin
    spec:
      serviceAccountName: canhazgpu-nodeagent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      containers:
      - name: kubeletplugin
        image: quay.io/dosmith/k8shazgpu-kubeletplugin:latest
        imagePullPolicy: Always
        args:
        - --node-name=$(NODE_NAME)
        - --cdi-root=/var/run/cdi
        - --num-devices=8
        - --kubelet-registrar-directory-path=/var/lib/kubelet/plugins_registry
        - --kubelet-plugins-directory-path=/var/lib/kubelet/plugins
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: plugins
          mountPath: /var/lib/kubelet/plugins
        - name: cdi
          mountPath: /var/run/cdi
        securityContext:
          privileged: true
      volumes:
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: plugins
        hostPath:
          path: /var/lib/kubelet/plugins
      - name: cdi
        hostPath:
          path: /var/run/cdi
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists